const ORIGIN = "http://localhost:5174";
const PK = process.env.PK, CID = process.env.CID;
const v = await (await fetch("http://localhost:9222/json/version")).json();
const ws = new WebSocket(v.webSocketDebuggerUrl);
let id=0; const pend=new Map();
const send=(method,params={},sid)=>new Promise(r=>{const i=++id;pend.set(i,r);ws.send(JSON.stringify({id:i,method,params,sessionId:sid}));});
await new Promise(r=>ws.onopen=r);
ws.onmessage=(m)=>{const d=JSON.parse(m.data); if(d.id&&pend.has(d.id)){pend.get(d.id)(d.result);pend.delete(d.id);}};
const {targetId}=await send("Target.createTarget",{url:"about:blank"});
const {sessionId}=await send("Target.attachToTarget",{targetId,flatten:true});
await send("Page.enable",{},sessionId); await send("Runtime.enable",{},sessionId);
await send("Page.navigate",{url:ORIGIN},sessionId);
await new Promise(r=>setTimeout(r,1500));
await send("Runtime.evaluate",{expression:`localStorage.setItem('sprout.parentKey','${PK}');localStorage.setItem('sprout.childId','${CID}');`},sessionId);
await send("Page.navigate",{url:ORIGIN+"/child/lesson"},sessionId);
await new Promise(r=>setTimeout(r,3500));
// build 1 group of 6 for the first question via DOM clicks
const click=(expr)=>send("Runtime.evaluate",{expression:expr},sessionId);
await click(`document.querySelectorAll('button').forEach(b=>{}); (function(){const add=[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Add a group')); if(add) add.click();})()`);
await new Promise(r=>setTimeout(r,400));
await click(`(function(){const pad=document.querySelector('[aria-label=\"Add counter\"]'); if(pad){for(let i=0;i<6;i++) pad.click();}})()`);
await new Promise(r=>setTimeout(r,500));
const {data}=await send("Page.captureScreenshot",{format:"png"},sessionId);
await Bun.write("/tmp/ss_workspace.png",Buffer.from(data,"base64"));
console.log("saved"); ws.close();
